# First Stage
FROM node:20.11-slim AS base

# Set the working directory
WORKDIR /app

# Copy package.json and yarn.lock to install dependencies
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn 

# Copy the rest of the application code
COPY . .


RUN yarn build

# second Stage
FROM  nginx:1.24-bullseye

COPY --from=base /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
