name: Backend Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  

jobs:

  build_docker_image:

    runs-on: [self-hosted, linux, ARM64]

    steps:
    - name: Checkout source code
    - uses: actions/checkout@v4
    
    - name: Build the Docker image of backend
      run: |
        cd Backend
        docker build -t ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }} -f Dockerfile.backend .
  
  tag_and_push_prod:
    runs-on: [self-hosted, linux, ARM64]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Tag Docker Image for Main
        run: |
          docker tag  ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:stable ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:$(git rev-parse --short "$GITHUB_SHA")
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:stable
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:$(git rev-parse --short "$GITHUB_SHA")

  
  tag_and_push_dev:
    runs-on: [self-hosted, linux, ARM64]
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Tag Docker Image for Dev
        run: |
          docker tag  ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:dev ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:$(git rev-parse --short "$GITHUB_SHA")
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:dev
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:$(git rev-parse --short "$GITHUB_SHA")
