name: Backend Docker Image CI

on:
  push:
    branches: [ "main" ]
  

jobs:

  build:

    runs-on: [self-hosted, linux, ARM64]

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image of backend
      run: |
        cd Backend
        sudo su ishwar
        docker build -t ishwarkhadka/backend:stable -t ishwarkhadka/backend:hash -f Dockerfile.backend .
      
