name: Backend Docker Image CI

on:
  push:
    branches: [ "main" ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image of backend
      run: docker build -t ishwarkhadka/backend:stable ./Backend/Dockerfile.backend .
      
