name: Backend Docker Image CI

on:
  push:
    branches: [ "main" ]
  

jobs:

  build:

    runs-on: [self-hosted, linux, ARM64]

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image of backend
      run: |
        cd Backend
        docker build -t ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:stable -t ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:hash -f Dockerfile.backend .
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin
        docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:stable
        docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:hash
        
      
