name: Frontend Deployment
on:
  push:
    branches: [ "frontend" ]
    
jobs:
  deploy_to_s3:
    runs-on: [self-hosted, linux, ARM64]
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
      
      
      - name: Install dependencies and build
        run: |
          cd Frontend
          yarn install
          yarn build

      - name: Deploying application to Amazon S3
        uses: dvelasquez/deploy-s3-action@main
        with:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
          AWS_BUCKET_NAME: ${{ secrets.S3_BUCKET }}
          BUCKET_PATH: "/"
          DIST_LOCATION_CODE: Frontend/dist

      - name: Invalidate CloudFront
        env:
          AWS_REGION: ${{ env.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}

        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
          
      - name: Increase Package Version
        run: |
          cd Frontend
          git config --global user.name ${{ vars.GIT_EMAIL }}
          git config --global user.name ${{ vars.GIT_USERNAME }}
          npm version patch
          cd ..
          git add .
          git commit -m "[skip ci] Increase version in frontend"
          git push -u origin frontend
        
