name: Frontend Deployment
on: 
  workflow_dispatch:

jobs:
  build_frontend:
    name: Build frontend
    runs-on: [self-hosted, linux, ARM64]
    steps:
      
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build:prod # will run `yarn build:prod` command
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test # will run `yarn test` command

      - name: Run test in sub-folder
        uses: borales/actions-yarn@v4
        with:
          cmd: test
          dir: 'frontend'
