name: CI
on: 
  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x  

      - name: Run build in sub-folder
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: 'Frontend'
