name: Frontend Deployment
on:
  push:
    branches: [ "frontend" ]
    
jobs:
  build_frontend:
    name: Build frontend
    runs-on: [self-hosted, linux, ARM64]
    steps:
      
      - name: Checkout source code
        uses: actions/checkout@v4
        
      - name: Build frontend
        run: |
          cd Frontend
          yarn build
