name: Frontend Deployment
on:
  push:
    branches: [ "frontend" ]
    
jobs:
  deploy_to_s3:
    runs-on: [self-hosted, linux, ARM64]
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
        - uses: actions/checkout@v4

        - name: Install dependencies
          run: |
            cd Frontend
            yarn

        - name: Build
          run: |
            cd Frontend
            yarn build

        - name: Deploy
          uses: lbertenasco/s3-deploy@v1
          with:
            folder: build
            bucket: ${{ secrets.S3_BUCKET }}
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: / *
          
