name: Frontend Deployment
on: 
  workflow_dispatch:

jobs:
  build_frontend:
    name: Build frontend
    runs-on: [self-hosted, linux, ARM64]
    steps:
      
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x  

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run build in sub-folder
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: 'Frontend'
